inspector/templates/base.html

Add favicon

---

docker-compose.yml
requirements/dev.txt

Use Gunicon's own reloader instead of hupper.

Fix reloader

---

inspector/main.py

Support .tar.gz files

---

inspector/main.py
requirements/main.in
requirements/main.txt

Sort versions

---

inspector/templates/code.html

Don't actually need this anymore. Fixes #17.

Remove safe filter

---

inspector/main.py
inspector/templates/base.html
inspector/templates/links.html

Add more links

---

inspector/main.py

Handle directories and binary files

---

inspector/main.py
requirements/deploy.in
requirements/main.in
requirements/main.txt

Add Sentry

---

inspector/main.py
inspector/templates/base.html

Link from release and package back to project page

---

inspector/main.py

Fixes https://sentry.io/organizations/python-software-foundation/issues/3433603853/

404 on missing zip file

---

inspector/main.py

Fixes https://sentry.io/organizations/python-software-foundation/issues/3542023411/?project=6528463&referrer=slack

404 for missing files

---

inspector/main.py

Fixes https://sentry.io/organizations/python-software-foundation/issues/3548751038/?project=6528463&query=is%3Aunresolved

Handle KeyError

---

inspector/main.py

Add return for zip file contents

---

inspector/main.py

Resolves https://sentry.io/organizations/python-software-foundation/issues/3572710222/

Abort with error on dist error response

---

inspector/main.py

Fixes https://sentry.io/organizations/python-software-foundation/issues/3587613626/.

Handle gunicorn exceptions

---

inspector/static/prism.css

Wraps incredibly long lines, while maintaining line numbers. 
Makes the CSS a bit easier to read as well.

Wrap lines

---

inspector/main.py
inspector/templates/base.html
inspector/templates/links.html

Specific commits detail the exact changes, but generally:
- less whitespace in rendered HTML
- adopt more semantic HTML https://web.dev/learn/html/semantic-html/

style: some html fixups

---

inspector/main.py
inspector/templates/base.html
inspector/templates/disasm.html
inspector/templates/index.html

- added search to base.html
- removed from index.html
Closes #121

added search to each page

---

inspector/static/style.css
inspector/templates/base.html
inspector/templates/code.html
inspector/templates/disasm.html
inspector/templates/index.html
inspector/templates/links.html

Restored the search bar with some stylistic improvements.

---

.gitpod.yml

Get template reloading and debug panels

chore(dev): use `flask run` in development

---

inspector/distribution.py
inspector/errors.py
inspector/main.py

Fixes:
- [INSPECTOR-2G](https://python-software-foundation.sentry.io/issues/6382832695/)
- [INSPECTOR-2H](https://python-software-foundation.sentry.io/issues/6384792707/)
- [INSPECTOR-2J](https://python-software-foundation.sentry.io/issues/6384865322/)

Handle exceptions from corrupted files

---

inspector/distribution.py

Fixes [INSPECTOR-2K](https://python-software-foundation.sentry.io/issues/6392299507/).

Handle BadGzipFile

---

inspector/distribution.py

Fixes [INSPECTOR-2N](https://python-software-foundation.sentry.io/issues/6417531257/).

Fix BadGzipFile import
